headers = {
    'Accept': '*/*',
    'Accept-Encoding': "gzip, deflate",
    'Accept-Language': 'en,en-US;q=0.9,vi;q=0.8',
    'Authorization': '',
    "Rr-Version": "1.12.1",
    "Content-Type": "application/json",
    'Priority': "u=1, i",
    'Origin': 'https://play.rockyrabbit.io',
    'Referer': 'https://play.rockyrabbit.io/',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Ch-Ua': '"Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    'Sec-Ch-Ua-mobile': '?1',
    'Sec-Ch-Ua-platform': '"Android"',
    'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
}